# Generated by Django 4.1.7 on 2023-04-04 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spells', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Spells',
            new_name='Spell',
        ),
    ]
